# This is a generated file. Not intended for manual editing.
services:
  inveonbootcampnveonbootcamp:
    build:
      context: "C:\\Inveon\\inveon-fullstack-bootcamp"
      dockerfile: "InveonBootcamp/Dockerfile"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/InveonBootcamp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "inveonbootcampnveonbootcamp:dev"
    ports: []
    volumes:
    - "C:\\Inveon\\inveon-fullstack-bootcamp\\InveonBootcamp:/app:rw"
    - "C:\\Inveon\\inveon-fullstack-bootcamp:/src:rw"
    - "C:\\Users\\Ege\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
